### ISSUE TITLE
10.0 redis clustering

### ISSUE THREAD

**Issue by chris93111** [sujiar37/AWX-HA-InstanceGroup#26]
Hi @sujiar37 

10.0 is available but i rabbitmq is replace by redis 

i have see redis cluster is possible with master an slave but i don't know if is target for the cluster awx
because is use socket 

https://github.com/ansible/awx/pull/6034/files

Do you have see ? do you have any idea of ​​integration of redis in the cluster ?

**Comment by chris93111** [comment]
i have maybe found awx it's now using postgres for inter-node communication i try and send feedback

**Comment by sebstyle** [comment]
Indeed 11.0.0 is the latest tag.
On each node local Redis communicates with local web sockets connected to the web interface.
Events relevant to the entire cluster are now communicated thru PostgreSQL.
In future versions Redis will most likely also replace the role of Memcached.

Custom clustering with RabbitMQ as this playbook provides seems to no longer be relevant.

**Comment by sebstyle** [comment]
https://github.com/ansible/awx/issues/5443

**Comment by chris93111** [comment]
@sebstyle yes clustering use notification postgresql for communication internode

**Comment by ryanpetrello** [comment]
Just chiming in - AWX isn't using any sort of redis clustering; every redis on every node is unaware of the others (if you all have questions, I'm happy to answer them).

**Comment by RylandDeGregory** [comment]
> Just chiming in - AWX isn't using any sort of redis clustering; every redis on every node is unaware of the others (if you all have questions, I'm happy to answer them).

Hi Ryan,

What is the high-level process for clustering Local Docker installations now that Redis is implemented and inter-node communication is done through PostgreSQL?

**Comment by moonrail** [comment]
I have clustered some AWX nodes by just writing a wrapper around the official role [local_docker](https://github.com/ansible/awx/tree/devel/installer/roles/local_docker)

I have not fully tested every feature, but these are the steps required that I know of:
- clone AWX-Repository by Tag on execution host to e.g. /tmp/awx
- create dir ~/.awx/awxcompose on target host
- copy [/tmp/awx/installer/roles/image_build/files/settings.py](https://github.com/ansible/awx/blob/devel/installer/roles/image_build/files/settings.py) to ~/.awx/awxcompose/settings.py on target host
- replace [CLUSTER_HOST_ID = "awx"](https://github.com/ansible/awx/blob/devel/installer/roles/image_build/files/settings.py#L31) of copied settings.py with your AWX nodes accessible FQDN, e.g. CLUSTER_HOST_ID = "host.domain.tld"
  - lineinfile with regexp did the trick for me
- note that your individual secrets should be the same across all nodes, so stuff them somewhere save, in a vault for example:
  - [secret_key](https://github.com/ansible/awx/blob/devel/installer/inventory#L120)
  - [admin_password](https://github.com/ansible/awx/blob/devel/installer/inventory#L112)
  - [broadcast_websocket_secret](https://github.com/ansible/awx/blob/devel/installer/roles/local_docker/tasks/main.yml#L4) - this is needed, as otherwise your AWX nodes can not communicate their events over /socket
- the only real "hack" here is the following:
  - we have to somehow include ~/.awx/awxcompose/settings.py in each awx_web & awx_task container
  - as [here](https://github.com/ansible/awx/blob/devel/installer/roles/local_docker/templates/docker-compose.yml.j2#L33) and [here](https://github.com/ansible/awx/blob/devel/installer/roles/local_docker/templates/docker-compose.yml.j2#L93) project_data_dir is used in volumes in docker-compose.yml, we can replace this with a multiline string, to give us another volume without needing to modify the official role local_docker
  - see below at passed vars to include_role for an basic example
- then just use Ansibles include_role and pass all vars, that are normally fetched from the inventory-file:
```yaml
- name: 'include official installation role "local_docker"'
  include_role:
    name: '/tmp/awx/installer/roles/local_role'
  vars:
    secret_key: '{{ lookup("your_secret_provider_plugin", "params") }}'
    admin_password: '{{ lookup("your_secret_provider_plugin", "params")}}'
    broadcast_websocket_secret: '{{ lookup("your_secret_provider_plugin", "params") }}'
    pg_hostname: 'your_postgres_server'
    project_data_dir: "      - \"~/.awx/awxcompose/settings.py\":\"/etc/tower/settings.py\"\n      - \"{{ your_desired_project_data_dir }}"
    (...)
```
